pluginManagement {
	repositories {
		google {
			content {
				includeGroupByRegex("com\\.android.*")
				includeGroupByRegex("com\\.google.*")
				includeGroupByRegex("androidx.*")
			}
		}
		mavenCentral()
		gradlePluginPortal()
		maven {
			url 'https://jitpack.io'
			content {
				includeGroupByRegex("com\\.github.*")
			}
		}
	}
}
dependencyResolutionManagement {
	repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
	repositories {
		google()
		mavenCentral()
		maven {
			url 'https://jitpack.io'
		}
	}
}

include ':app', ':kotatsu-parsers-redo', ':kotatsu-parsers-ksp'

project(':kotatsu-parsers-redo').projectDir = new File('/Users/alisha/Kotatsu-Development/kotatsu-parsers-redo')
project(':kotatsu-parsers-ksp').projectDir = new File('/Users/alisha/Kotatsu-Development/kotatsu-parsers-redo/kotatsu-parsers-ksp')


rootProject.name = "Kotatsu"
